spring:
  profiles:
    active:
    - dev

---
server:
  port: 1234
spring:
  profiles: dev
  application:
      name: dev-enviroment
properties:
  test: dev-properties

---
server:
  port: 5678
spring:
  profiles: test
  application:
      name: test-enviroment
properties:
  test: test-properties
